DROP TABLE Day						CASCADE;
DROP TABLE Query					CASCADE;
DROP TABLE Player_Meets_Requirement CASCADE;
DROP TABLE Requirement				CASCADE;
DROP TABLE Player					CASCADE;
DROP TABLE Ranking					CASCADE;
DROP TABLE Employee 				CASCADE;





